abi: export symbols in whitelist for Ironman DP feature
Fix the following user build failure after integration of the Ironman DP
feature:

ERROR: modpost: "tcpm_set_port_altmode" [drivers/usb/typec/tcpm/fusb302.ko] undefined!
ERROR: modpost: "tcpm_typec_port_get" [drivers/usb/typec/tcpm/fusb302.ko] undefined!
ERROR: modpost: "typec_altmode_unregister_driver" [drivers/usb/typec/altmodes/typec_displayport.ko] undefined!
ERROR: modpost: "__typec_altmode_register_driver" [drivers/usb/typec/altmodes/typec_displayport.ko] undefined!
ERROR: modpost: "typec_altmode_exit" [drivers/usb/typec/altmodes/typec_displayport.ko] undefined!
ERROR: modpost: "typec_altmode_enter" [drivers/usb/typec/altmodes/typec_displayport.ko] undefined!
ERROR: modpost: "typec_get_negotiated_svdm_version" [drivers/usb/typec/altmodes/typec_displayport.ko] undefined!
ERROR: modpost: "typec_altmode_vdm" [drivers/usb/typec/altmodes/typec_displayport.ko] undefined!
ERROR: modpost: "typec_altmode_notify" [drivers/usb/typec/altmodes/typec_displayport.ko] undefined!
ERROR: modpost: "typec_get_portid" [drivers/usb/typec/altmodes/typec_displayport.ko] undefined!
ERROR: modpost: "typec_get_orientation" [drivers/usb/typec/altmodes/typec_displayport.ko] undefined!
ERROR: modpost: "typec_altmode2port" [drivers/usb/typec/altmodes/typec_displayport.ko] undefined!

Ironman does not require GKI compliance test. Meantime those symbols are
not used by Hiphi and Li. So all the products should be safe after this
abi change

Change-Id: I8dae1702bc8b10ddf955c0b907be587c07d8e03b
Reviewed-on: https://gerrit.mot.com/2118464
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Konstantin Makariev <kmakariev@motorola.com>
Submit-Approved: Jira Key