ANDROID: GKI: Remove pfn_valid symbol
We are switching to the generic pfn_valid function and the
arm64-specific one is being removed.

ERROR: Differences between ksymtab and symbol list detected!
Symbols missing from ksymtab:
 - pfn_valid

Conflicts:
	android/abi_gki_aarch64_qcom

Bug: 228454859
Change-Id: Ie06dfff77d917cbac02033c4b3486b121c8b2b7b
Signed-off-by: Georgi Djakov <quic_c_gdjako@quicinc.com>
Signed-off-by: Blagovest Kolenichev <quic_c_bkolen@quicinc.com>
Signed-off-by: Bruce Levy <quic_blevy@quicinc.com>