: Fix user build error due to Ironman // Kernel & DT cleanup
Fix the following user build failure after cleanup of the Ironman DP
feature:

ERROR: modpost: "tcpm_msg2string" [drivers/usb/typec/tcpm/fusb302.ko]
undefined!

Change-Id: I61d8d37926a6f93c4896dc3ceb987e58c82ece5c
Reviewed-on: https://gerrit.mot.com/2162906
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Rohit Sisodia <rohits@motorola.com>
Tested-by: Rohit Sisodia <rohits@motorola.com>
Reviewed-by: Konstantin Makariev <kmakariev@motorola.com>
Submit-Approved: Rohit Sisodia <rohits@motorola.com>